frase=('    Ola Mundo')
print('A frase escolhida tem: ', len(frase), 'letras')
print(frase[2])
print(frase[0:4])
print(frase[4:])
print(frase[:9])
print(frase.replace('ola mundo', 'hello world'))
print(frase.upper())
print(frase.lower())
print(frase.strip())